download_test:
	mkdir test_data
	wget -r -P "test_data" ftp://massive.ucsd.edu/MSV000084402/raw/SRM1950_20min_88_01_6950.d

run_test:
	python client.py --input test/data/massive.ucsd.edu/MSV000084402/raw/SRM1950_20min_88_01_6950.d